// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdwG7avcJTDlzpgI42E4iSjuEgoPS848Q',
    appId: '1:332551198145:web:03f32217b8580f90480b40',
    messagingSenderId: '332551198145',
    projectId: 'currency-converter-92ab2',
    authDomain: 'currency-converter-92ab2.firebaseapp.com',
    storageBucket: 'currency-converter-92ab2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChtL0X9Q6-hPuylja6scqZJGgux7qPYtw',
    appId: '1:332551198145:android:b4573e5df44a90ec480b40',
    messagingSenderId: '332551198145',
    projectId: 'currency-converter-92ab2',
    storageBucket: 'currency-converter-92ab2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC22tNLNX4EKUr1Ane-roExofoiLDIIPzQ',
    appId: '1:332551198145:ios:1acb3a1da644ee66480b40',
    messagingSenderId: '332551198145',
    projectId: 'currency-converter-92ab2',
    storageBucket: 'currency-converter-92ab2.firebasestorage.app',
    iosBundleId: 'com.example.currConverter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC22tNLNX4EKUr1Ane-roExofoiLDIIPzQ',
    appId: '1:332551198145:ios:1acb3a1da644ee66480b40',
    messagingSenderId: '332551198145',
    projectId: 'currency-converter-92ab2',
    storageBucket: 'currency-converter-92ab2.firebasestorage.app',
    iosBundleId: 'com.example.currConverter',
  );
}
